### ISSUE TITLE
The repository and the associated blogpost use the deprecated "Jenkins master" terminology

### ISSUE THREAD

**Issue by oleg-nenashev** [spy86/docker-jenkins-controller-node#1]
Hi @spy86 , thanks for the nice blogpost in https://iceburn.medium.com/jenkins-configuration-as-code-afd9031a42c9. Just noticed it in https://twitter.com/iced_burn/status/1393094558871924736

I would be happy to repost it in Jenkins social media channels, but unfortunately the blogpost uses the deprecated "master" terminology in this repository and in the blogpost. The new term is "controller", effective since Aug 2020. We have a policy of not reposting articles using the deprecated terminology. FTR https://cd.foundation/blog/2020/08/25/jenkins-terminology-changes/ for more info.

It would be great if you could update the repository and the blogpost

**Comment by spy86** [comment]
Hi @oleg-nenashev thanks for the information about deprecated terminology I updated the repository and blog post with the new names.

**Comment by oleg-nenashev** [comment]
Thanks a lot for the fix!
